name: Run random player

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_random_player:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
           version: "0.8"

      # - name: Set up Python
      #   run: uv python install

      - name: Run random player
        run: uv run main.py --player r --import-cake cakes/rectangle.csv --seed 0
